apiVersion: v1
kind: ConfigMap
metadata:
  name: is-reconstruction-5
  namespace: default
data:
  config: |-
    {
        "broker_uri": "amqp://rabbitmq.default",
        "detection":{
            "id":5,
            "detection_type":"ArUco",
            "aruco_height": 0.29,
            "time_wait_for_detection":0.05,
            "estimate_position_with_only_one_detection": "True"
        }
    }
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "is-reconstruction"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: is-reconstruction
    spec:
      containers:
        - name: is-reconstruction
          image: matheusdutra0207/is-reconstruction:v4
          command: ["python"]
          args: ["service.py", "../etc/config/options.json", "../etc/calibration/hd/camera-calibrations/labsea/"]
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
          volumeMounts:
            - name: options
              mountPath: /opt/etc/config/
            - name: calibrations
              mountPath: /opt/etc/calibration/hd         
      volumes:
        - name: options
          configMap:
            name: is-reconstruction-5
            items:
              - key: config
                path: options.json
        - name: calibrations
          gitRepo:
            repository: "https://github.com/vinihernech/camera-calibrations"
            # revision: a9ad7329bf14d4cf161f5e3f21ceb7297708b210
            revision: 15c13c541bb6a39f27992b7ab1762b5b56590f25                
